---
- name: Allow UFW ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ ufw_allowed_ports }}"

- name: Configure UFW state
  community.general.ufw:
    state: "{{ ufw_state }}"

- name: Start docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
